"""empty message

Revision ID: e88df48d60cd
Revises: d81bed2e456b
Create Date: 2019-03-14 15:37:45.932303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88df48d60cd'
down_revision = 'd81bed2e456b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ih_facility_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ih_house_facility',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['ih_facility_info.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['ih_house_info.id'], ),
    sa.PrimaryKeyConstraint('house_id', 'facility_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ih_house_facility')
    op.drop_table('ih_facility_info')
    # ### end Alembic commands ###
